version: '3'

services:  
  app:
    build: ./app
    environment:
      SENTRY_DSN: ${ENV_SENTRY_DSN} 
    env_file:
      ./.sentry_env
    ports:
      - 3333:3333 
  
  proxy:
    image: nginx:1.19
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
